### ISSUE TITLE
Error: No pubspec.yaml file found

### ISSUE THREAD

**Issue by buraktabn** [sakebook/actions-flutter-pub-publisher#21]
```
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

I've tried `flutter pub publish --dry-run` and it finds no error. You can find the raw logs in this [gist](https://gist.github.com/buraktabn/c4315819b55fef90e92ab400926455ea). Also, I've updated my secret since issue #16 solved the issue by editing it but no luck for me.

**actions.yml**
```yml
- name: Publish Dart/Flutter package
  uses: sakebook/actions-flutter-pub-publisher@v1.3.1
  with:
    credential: ${{ secrets.DART_PUB_CREDENTIAL_JSON }}
    flutter_package: true
    skip_test: true
    dry_run: true
```
