### ISSUE TITLE
Can not deploy from CI with personal credentials.json

### ISSUE THREAD

**Issue by danielgomezrico** [sakebook/actions-flutter-pub-publisher#30]
Hi

I have the YML like this:

```yaml
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.PUBSPEC_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: true
```

And when I try to run the job on ci it stays forever here:

```bash
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A37523&code_challenge=UrnqtnQNfQ_0420cPMO1I-fTDajsfdvzcsGUaKgbXFE&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".
```

Im using my personal json here, what can I do?

I found this that may be related:
- https://github.com/dart-lang/pub-dev/issues/5388
