### ISSUE TITLE
pub: not found error when flutter_package: false

### ISSUE THREAD

**Issue by festelo** [sakebook/actions-flutter-pub-publisher#32]
action.yml
```yaml
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./h3_dart
```

log.txt
```sh
Check credentials
OK
Copy credentials
/home/cirrus/entrypoint.sh: 65: pub: not found
OK
Switching to package directory
Skip test
Executing package validation
```
